# lemon token header file --> C routine to convert int to token name

BEGIN {
	print ""
	print "// Generated by tokentos.awk"
	print "const char *"
	print "tokentos(int token)"
	print "{"
	print "	switch (token) {"
}

/^#define / {
	tokenname = $2
	intval = $3
	printf "	case %d: return \"%s\"; break;\n", intval, tokenname
}

END {
	print "	default: errx(1, \"unexpected token %d\", token); break;"
	print "	}"
	print "}"
	print ""
}
