	CFLAGS := $(CFLAGS) -std=c99
CC=/usr/bin/cc

all:  dateparser.o

dateparser.o: dategrammar.c dateparser.c

#
# Don't use dategrammar.h as a target
# as the header file is not regenerated by
# lemon if there was no change in tokens names. 
# Using dategrammar.c is sufficient
# becase generating .c will always create the .h as well.
# 
dategrammar.c: dategrammar.y lemon
	./lemon dategrammar.y


# Prevent yacc from trying to build parsers.
# http://stackoverflow.com/a/5395195/79202
#%.c: %.y

lemon: lemon.c
	${CC} -o lemon lemon.c

test:
	(cd regress ; make )


clean:
	rm -f *.o
	rm -f *.out
	rm -f dategrammar.c dategrammar.h
	rm -f  lemon
	(cd regress ; make clean)
